name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:
    inputs:
      run_job:
        description: "Run Specific Job"
        type: boolean
        required: false
        default: false
      custom_message:
        description: "Enter a custom message"
        type: string
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Exploring Workflow Dispatch Trigger"

  job2:
    if: ${{ github.event.inputs.run_job == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: "Printing Custom Message"
        run: echo "${{ github.event.inputs.custom_message }}"
